import type { Metadata } from "next";
import { Providers } from "../lib/Providers";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className="p-4">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
